### ISSUE TITLE
Two issues in the Mistral tutorial

### ISSUE THREAD

**Issue by MaximeSchubiger** [UbiOps/tutorials#2]
Hi,

I found two issues in your Mistral tutorial that might be useful to fix in order to prevent other people from running into them as well.

On line 354:
https://github.com/UbiOps/tutorials/blob/bd2325af6aa48b467f5afefb4dfb91d14ecb3193/huggingface-mistral7b/huggingface-mistral7b/mistral_7b_deployment.ipynb#L354
It should be "max_new_tokens" instead of "max_new_token".

And on line 504:
https://github.com/UbiOps/tutorials/blob/bd2325af6aa48b467f5afefb4dfb91d14ecb3193/huggingface-mistral7b/huggingface-mistral7b/mistral_7b_deployment.ipynb#L504
I don't know it was intentional to leave it out, but I think it would be useful to already fill in the model id of the model that your loading from HuggingFace. So it should read "MODEL_ID = "mistralai/Mistral-7B-Instruct-v0.2"" instead of just "MODEL_ID =".

**Comment by anoukdutree-ubiops** [comment]
Hi @MaximeSchubiger,

Thank you so much for raising this issue. We will patch it!

**Comment by anoukdutree-ubiops** [comment]
This issue has been resolved with the latest change. Thanks again for informing us.
